# Cloudflare Pages configuration
name = "lemans-frontend"
compatibility_date = "2023-05-18"
pages_build_output_dir = "out"
node_compat = true

[build]
command = "npm run build:cloudflare"
cwd = "."

[build.environment_variables]
NODE_VERSION = "18"

[[env_vars]]
# Add environment variables here
# NEXT_PUBLIC_SUPABASE_URL = "your-supabase-url"
# NEXT_PUBLIC_SUPABASE_ANON_KEY = "your-supabase-anon-key"
# SUPABASE_SERVICE_ROLE_KEY = "your-service-role-key"
# STRIPE_SECRET_KEY = "your-stripe-secret-key"
# DATABASE_URL = "your-database-url"
# NEXT_PUBLIC_WEBSITE_URL = "your-website-url"